import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import mongoose from 'mongoose';
import { z } from 'zod';
import { connectDatabase } from './config/db.js';
import User from './models/User.js';
import Store from './models/Store.js';
import Rating from './models/Rating.js';

const app = express();
const port = Number(process.env.PORT || 5000);
const roles = ['ADMIN', 'NORMAL_USER', 'STORE_OWNER'];
const passwordRule = z.string().min(8).max(16).regex(/[A-Z]/, 'must contain an uppercase letter').regex(/[^A-Za-z0-9]/, 'must contain a special character');
const nameRule = z.string().trim().min(20).max(60);
const userInput = z.object({ name: nameRule, email: z.string().email(), address: z.string().trim().max(400), password: passwordRule });
const loginInput = z.object({ email: z.string().email(), password: z.string().min(1) });
const ratingInput = z.object({ value: z.number().int().min(1).max(5) });
const storeInput = z.object({ name: nameRule, email: z.string().email(), address: z.string().trim().max(400), ownerId: z.string().min(1) });
const response = (res, data, message = 'Success', status = 200) => res.status(status).json({ success: true, message, data });
const errorResponse = (res, message, status = 400, errors = []) => res.status(status).json({ success: false, message, errors });
const profile = (user) => ({ id: user._id.toString(), name: user.name, email: user.email, address: user.address, role: user.role });
const auth = (req, res, next) => { const token = req.headers.authorization?.startsWith('Bearer ') && req.headers.authorization.slice(7); if (!token) return errorResponse(res, 'Authentication required', 401); try { req.user = jwt.verify(token, process.env.JWT_SECRET); next(); } catch { return errorResponse(res, 'Invalid or expired session', 401); } };
const authorize = (...allowed) => (req, res, next) => allowed.includes(req.user.role) ? next() : errorResponse(res, 'You do not have permission to perform this action', 403);
const validate = (schema, source = 'body') => (req, res, next) => { const parsed = schema.safeParse(req[source]); if (!parsed.success) return errorResponse(res, 'Validation failed', 400, parsed.error.issues.map((e) => ({ field: e.path.join('.'), message: e.message }))); req[source] = parsed.data; next(); };
const validId = (id) => mongoose.isValidObjectId(id);
const pagination = (req) => { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 10)); return { page, limit, skip: (page - 1) * limit }; };
const sortSpec = (value, allowed, fallback = 'createdAt') => ({ [allowed.includes(value) ? value : fallback]: value === 'desc' ? -1 : 1 });
const average = (value) => value == null ? null : Math.round(value * 10) / 10;
const averageForStore = async (storeId) => { const [result] = await Rating.aggregate([{ $match: { store: new mongoose.Types.ObjectId(storeId) } }, { $group: { _id: null, averageRating: { $avg: '$value' }, totalRatings: { $sum: 1 } } }]); return { averageRating: average(result?.averageRating), totalRatings: result?.totalRatings || 0 }; };

app.use(helmet()); app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' })); app.use(express.json());
app.use('/api/auth', rateLimit({ windowMs: 15 * 60 * 1000, limit: 60 }));
app.get('/api/health', (_, res) => response(res, { status: 'ok', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected' }));
app.post('/api/auth/signup', validate(userInput), async (req, res, next) => { try { const user = await User.create({ ...req.body, password: await bcrypt.hash(req.body.password, 10), role: 'NORMAL_USER' }); response(res, profile(user), 'Account created', 201); } catch (e) { next(e); } });
app.post('/api/auth/login', validate(loginInput), async (req, res, next) => { try { const user = await User.findOne({ email: req.body.email }).select('+password'); if (!user || !(await bcrypt.compare(req.body.password, user.password))) return errorResponse(res, 'Invalid email or password', 401); response(res, { token: jwt.sign({ userId: user._id.toString(), role: user.role }, process.env.JWT_SECRET, { expiresIn: '8h' }), user: profile(user) }, 'Signed in'); } catch (e) { next(e); } });
app.patch('/api/auth/update-password', auth, validate(z.object({ currentPassword: z.string(), newPassword: passwordRule })), async (req, res, next) => { try { const user = await User.findById(req.user.userId).select('+password'); if (!user || !(await bcrypt.compare(req.body.currentPassword, user.password))) return errorResponse(res, 'Current password is incorrect'); user.password = await bcrypt.hash(req.body.newPassword, 10); await user.save(); response(res, null, 'Password updated'); } catch (e) { next(e); } });

app.get('/api/admin/dashboard-stats', auth, authorize('ADMIN'), async (_, res, next) => { try { const [totalUsers, totalStores, totalRatings] = await Promise.all([User.countDocuments(), Store.countDocuments(), Rating.countDocuments()]); response(res, { totalUsers, totalStores, totalRatings }); } catch (e) { next(e); } });
app.post('/api/admin/users', auth, authorize('ADMIN'), validate(userInput.extend({ role: z.enum(roles) })), async (req, res, next) => { try { const user = await User.create({ ...req.body, password: await bcrypt.hash(req.body.password, 10) }); response(res, profile(user), 'User created', 201); } catch (e) { next(e); } });
app.get('/api/admin/users', auth, authorize('ADMIN'), async (req, res, next) => { try { const { page, limit, skip } = pagination(req); const and = []; if (req.query.search) and.push({ $or: ['name', 'email', 'address'].map((field) => ({ [field]: { $regex: req.query.search, $options: 'i' } })) }); for (const field of ['name', 'email', 'address']) if (req.query[field]) and.push({ [field]: { $regex: req.query[field], $options: 'i' } }); if (roles.includes(req.query.role)) and.push({ role: req.query.role }); const filter = and.length ? { $and: and } : {}; const [items, total] = await Promise.all([User.find(filter).select('-password').sort(sortSpec(req.query.sortBy, ['name','email','address','role','createdAt'])).skip(skip).limit(limit).lean(), User.countDocuments(filter)]); response(res, { items: items.map(profile), pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } }); } catch (e) { next(e); } });
app.get('/api/admin/users/:id', auth, authorize('ADMIN'), async (req, res, next) => { try { if (!validId(req.params.id)) return errorResponse(res, 'Invalid user id', 400); const user = await User.findById(req.params.id).select('-password').lean(); if (!user) return errorResponse(res, 'User not found', 404); const result = { ...profile(user) }; if (user.role === 'STORE_OWNER') { const store = await Store.findOne({ owner: user._id }).lean(); result.store = store ? { id: store._id, name: store.name, email: store.email, address: store.address, ...(await averageForStore(store._id)) } : null; } response(res, result); } catch (e) { next(e); } });
const storeFilter = (query) => { const and = []; if (query.search) and.push({ $or: ['name', 'email', 'address'].map((field) => ({ [field]: { $regex: query.search, $options: 'i' } })) }); for (const field of ['name', 'email', 'address']) if (query[field]) and.push({ [field]: { $regex: query[field], $options: 'i' } }); return and.length ? { $and: and } : {}; };
const listStores = async (req, userId) => { const { page, limit, skip } = pagination(req); const filter = storeFilter(req.query); const stores = await Store.find(filter).sort(sortSpec(req.query.sortBy, ['name','email','address','createdAt'])).skip(skip).limit(limit).lean(); const ids = stores.map((store) => store._id); const aggregates = await Rating.aggregate([{ $match: { store: { $in: ids } } }, { $group: { _id: '$store', averageRating: { $avg: '$value' } } }]); const averages = Object.fromEntries(aggregates.map((item) => [item._id.toString(), average(item.averageRating)])); let own = {}; if (userId && ids.length) { const ratings = await Rating.find({ user: userId, store: { $in: ids } }).lean(); own = Object.fromEntries(ratings.map((rating) => [rating.store.toString(), rating.value])); } const total = await Store.countDocuments(filter); return { items: stores.map((store) => ({ id: store._id, name: store.name, email: store.email, address: store.address, overallRating: averages[store._id.toString()] ?? null, ...(userId ? { userSubmittedRating: own[store._id.toString()] ?? null } : {}) })), pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } }; };
app.post('/api/admin/stores', auth, authorize('ADMIN'), validate(storeInput), async (req, res, next) => { try { if (!validId(req.body.ownerId)) return errorResponse(res, 'Invalid owner id', 400); const owner = await User.findOne({ _id: req.body.ownerId, role: 'STORE_OWNER' }); if (!owner) return errorResponse(res, 'Owner must be an existing store owner', 400); const store = await Store.create({ name: req.body.name, email: req.body.email, address: req.body.address, owner: owner._id }); response(res, store, 'Store created', 201); } catch (e) { next(e); } });
app.get('/api/admin/stores', auth, authorize('ADMIN'), async (req, res, next) => { try { response(res, await listStores(req)); } catch (e) { next(e); } });
app.get('/api/stores', auth, authorize('NORMAL_USER'), async (req, res, next) => { try { response(res, await listStores(req, req.user.userId)); } catch (e) { next(e); } });
app.post('/api/stores/:storeId/rate', auth, authorize('NORMAL_USER'), validate(ratingInput), async (req, res, next) => { try { if (!validId(req.params.storeId)) return errorResponse(res, 'Invalid store id', 400); if (!await Store.exists({ _id: req.params.storeId })) return errorResponse(res, 'Store not found', 404); const rating = await Rating.findOneAndUpdate({ user: req.user.userId, store: req.params.storeId }, { value: req.body.value }, { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }); response(res, { rating: { id: rating._id, value: rating.value }, ...(await averageForStore(req.params.storeId)) }, 'Rating saved'); } catch (e) { next(e); } });
app.get('/api/owner/dashboard', auth, authorize('STORE_OWNER'), async (req, res, next) => { try { const store = await Store.findOne({ owner: req.user.userId }).lean(); if (!store) return errorResponse(res, 'No store is assigned to this account', 404); const ratings = await Rating.find({ store: store._id }).populate('user', 'name email').sort({ updatedAt: -1 }).lean(); const summary = await averageForStore(store._id); response(res, { store: { id: store._id, name: store.name, email: store.email, address: store.address }, ...summary, ratings: ratings.map((rating) => ({ id: rating._id, user: rating.user, value: rating.value, createdAt: rating.createdAt, updatedAt: rating.updatedAt, date: rating.updatedAt })) }); } catch (e) { next(e); } });

app.use((err, _req, res, _next) => { if (err.name === 'ValidationError') return errorResponse(res, 'Validation failed', 400, Object.values(err.errors).map((item) => ({ field: item.path, message: item.message }))); if (err.name === 'CastError') return errorResponse(res, 'Invalid identifier', 400); if (err.code === 11000) return errorResponse(res, 'A record with that unique value already exists', 409); console.error(err); return errorResponse(res, 'An unexpected server error occurred', 500); });
async function start() { await connectDatabase(); app.listen(port, () => console.log(`API listening on http://localhost:${port}`)); }
start().catch((error) => { console.error(`Unable to start application: ${error.message}`); process.exit(1); });
